version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: 
      - start-dev 
      - --import-realm 
      - --hostname=keycloak 
      - --hostname-strict=false
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  revenda-db:
    image: postgres:latest
    container_name: revenda-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  revenda-api:
    build: .
    container_name: revenda-api
    ports: 
      - "8081:8081"
    environment:
      DB_CONN_STR: jdbc:postgresql://revenda-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_ISSUER_URI: http://keycloak:8080/realms/revenda
      JWT_JWK_URI: http://keycloak:8080/realms/revenda/protocol/openid-connect/certs
    depends_on:
      - revenda-db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:8082"
    depends_on:
      - keycloak

volumes:
  keycloak_data:
  pgdata:
